dashboard/app.rb
dashboard/assets/scripts/Dashboard.hx
dashboard/assets/scripts/Makefile
dashboard/assets/scripts/dashboard.js
dashboard/dashboard.html
dashboard/dashboard3.html
dashboard/resources/dashboard.rb

This adds a dashboard 3.0 but along the existing dashboard with a "try beta" link. 3.0 is meant to look fancy and work in mobile. But CPU usage is higher on desktop so it isn't a competitive replacement in that regard.

Add dashboard 3.0 as a beta

---

viewer/archivebotviewer/web.py

This eases programmatic access to the viewer's database, e.g.
curl -s 'http://HOST/index.json?q=tumblr' | jq '[.results[].domain]'

viewer: Add JSON interface to search endpoint

---

bot/job_status_generation.rb

to make various auto-linkers happy

Add a space between the URL and the surrounding parens

---

bot/job_options_parser.rb
spec/bot/job_options_parser_spec.rb

also fix tests for really old version of rspec

Fix aliases for options with arguments; add tests

---

uploader/uploader.py

I noticed that my pipeline's disk was filling up with WARCs because the uploader had crashed. Turns out that it was trying to use a variable that only gets defined in s3 mode.

uploader: Fix UnboundLocalError when not in s3 mode

---

pipeline/archivebot/seesaw/tasks.py
pipeline/archivebot/wpull/settings.py

Fix partial removal of archivebot.control.ConnectionError

---

INSTALL.pipeline
db/ignore_patterns/global.json
db/ignore_patterns/reddit.json

Adds pinterest join and archive.is to global ignores, and out.reddit.com (redundant tracking) to reddit ignores.  Improves and updates documentation on how to install and run a pipeline.

Add to igsets and improve pipeline documentation

---

uploader/uploader.py

Change IA S3 uploader to add metadata "sponsor:Internet Archive"

---

.travis.yml
Gemfile
Gemfile.lock
dashboard/app.rb
pipeline/pipeline.py
test/integration_runner.py
test/run_dashboard.sh
test/run_firehose.sh

Do all sorts of cruft in order to get the integration test to run again as a whole.
See https://travis-ci.org/Sanqui/ArchiveBot/builds/242448366.
The only remaining issue is that the dashboard crashes on shutdown, but that's not of much concern.

Restore the integration test

---

doc/commands.rst

updated documentation

---

doc/admin.rst
doc/index.rst

added new control node documentation, linked redis documentation

added new control node documentation, linked redis documentation

---

doc/admin.rst

moar minor text edits

---

dashboard/dashboard.html

This brings in some dashboard improvements [made in grab-site](https://github.com/ludios/grab-site/commits/master/libgrabsite/dashboard.html):
- context menu support for Safari
- alignment fixes
- styling tweaks
- other minor fixes

Import grab-site's dashboard fixes

---

bot/brain.rb
dashboard/app.rb
dashboard/resources/pending.rb

Add pending job list to the dashboard and disable !pending when the queue is long

---

db/user_agents/chrome.json

Add macOS Chrome UA

---

db/ignore_patterns/blogs.json

- Fix CSI ignore on Blogspot, and remove search and label ignore since those pages are actually needed for navigation
- Add ignore for reverse pagination
- Ignore wordpress.com login

A few blogs igset improvements

---

db/user_agents/chrome.json
db/user_agents/edge.json
db/user_agents/firefox.json
db/user_agents/safari.json

Mostly based on https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
Couldn't find the current values for all UAs listed here, so I left those alone.

Update user agents to current versions

---

pipeline/archivebot/seesaw/tasks.py

Verify that inexistent domains do not resolve

---

pipeline/archivebot/seesaw/tasks.py
pipeline/pipeline.py

Check for local webservers

---

pipeline/archivebot/control.py

* Fix log shipper getting crashed by Redis errors that are not connection-related (e.g. ResponseError when the control node runs out of disk and Redis's disk dumper fails)
* Limit the log queue size to 10k messages to avoid running out of memory if messages can't be shipped for a prolonged period of time.
Fixes #323

Fix log shipper crash

---

pipeline/archivebot/seesaw/monitoring.py

… instead of after having started all GetItemFromQueue tasks

Register pipeline immediately on startup

---

INSTALL.pipeline
pipeline/pipeline.py

This requires at least git 2.6.0 due to `--date=format:x`

Get the pipeline version automatically from git

---

pipeline/archivebot/seesaw/tasks.py
pipeline/pipeline.py

Verify that the version number hasn't changed since the pipeline was started

---

bot/brain.rb

Check that an absolute URL with a host was provided

---

dashboard/assets/scripts/Dashboard.hx
dashboard/assets/scripts/dashboard.js
dashboard/dashboard.html

Fix connection to WebSocket when accessing the dashboard over a non-standard port

---

bot/pipeline_notifier.rb

Prevent pipeline spam on bot startup

---

dashboard/resources/ignores.rb

Based on zino's (@PeterBortas) implementation in Pike: https://gist.githubusercontent.com/PeterBortas/f0799a4951a8b857a3dbc6fe6855000b/raw/ceb18cc531f14c6c06b0a0be320a04afa87bf62b/ignore-web.pike

Add compact ignore list view which collapses based on the existing igsets

---

db/ignore_patterns/dreamwidth.json

Updated most of the existing ignores to be more precise, and added a large number of ignores appearing in particular on LJ (login, member-only functions, calendar recursion, various broken stuff due to JS extraction or simply broken links).

Extend and update Dreamwidth/LiveJournal igset

---

bot/summary.rb

Followup for #444 because I don't understand Ruby variable scopes and our test suite doesn't cover `!status`.

Fix other pending counter

---

db/ignore_patterns/tistory.json

Add Tistory igset

---

db/ignore_patterns/tistory.json

Not present on all blogs. Example: https://zprooo915.tistory.com/

Ignore infinite calendar pagination on Tistory

---

db/ignore_patterns/tistory.json

E.g. https://www.bycpp.net/ == https://fastaping.tistory.com/

Support custom domains on Tistory

---

db/ignore_patterns/tistory.json

Seen on job 3h6rd07y9m1rxpyrnbjpkb8h6

Ignore another version of Tistory login URLs

---

db/ignore_patterns/global.json

Ignore another CBL sinkhole domain

---

dashboard/finished.html

* Add Remaining column to finished job list
* Clean up Responses column code

Improvements to the list of recently finished jobs

---

db/ignore_patterns/badvideos.json

Add IGN and MLB to badvideos

---

pipeline/requirements.txt

https://github.com/ArchiveTeam/wpull/issues/463

Pin SQLAlchemy version to <1.4

---

db/ignore_patterns/notweets.json

add twitter's new domain, x.com
