pipeline/archivebot/dupespotter/dupes.py, pipeline/archivebot/dupespotter/dupespotter.py, pipeline/archivebot/seesaw/wpull.py, pipeline/archivebot/wpull/plugin.py, pipeline/pipeline.py, pipeline/requirements.txt
This adds dupespotting code from ludios/wpull@fd9d7ad into archivebot's package and uses it as a "plugin" in Wpull. This means the hax branch is no longer needed and the dupespotting code needs to be updated here.
This also adds `--strip-session-id`, for removing session IDs from URLs, and  `--escaped-fragment`, for supporting `#!` URLs.
=> pipeline: Wpull with dupespotter plugin, escaped fragment, strip session ID

dashboard/dashboard3.html
Use max-height so that in "narrow mode", it collapses
Extend height-limit-big to show the full summary (for jobs with 0 or 1 line of notes)
=> CSS fixes for beta interface height-limit

db/ignore_patterns/global.json
warnerbros.com/[number] always redirect to a 404 page.
Something on the Internet generate a lot of these links and ArchiveBot waste time getting the same error page again and again.
=> Ignore broken link to warnerbros.com

dashboard/pipeline.html, pipeline/archivebot/seesaw/monitoring.py, pipeline/pipeline.py
This creates an column on the pipeline dashboard page that states whether a pipeline is running or in the process of gracefully stopping.  On the backend, two event handlers were added to facilitate that change in status.
=> Report pipeline status

db/ignore_patterns/twitter.json
This should prevent twitter jobs from endlessly downloading [\?&]nav= and other crazy stuff.
=> Fix twitter ignore set.

bot/add_ignore_sets.rb
I have not tested this, as I haven't set up the environment for it yet.
=> The hooked call to add_ignore_sets doesn't need to re-check authorization

db/ignore_patterns/global.json
"^https?://www\.tumblr\.com/(impixu\?|share(/link/?)?\?|reblog/)" was failing
to match URLs such as "https://px.srvcs.tumblr.com/impixu?".
If the new ignore is too broad or inefficient, one could instead specifically match px.srvcs.tumblr.com/impixu, since that's really the only thing I see the current one missing on a regular basis.
=> Expand global tumblr ignore to cover other subdomains

pipeline/archivebot/seesaw/wpull.py, pipeline/pipeline.py, pipeline/requirements.txt, uploader/uploader.py
FOS is a bottleneck at the moment, and it looks like we can actually get away with simply uploading the files to the collection, one item per pipeline per calendar date with many WARCs, and have essentially the same result we have now.  This patch adds a new mode of operation for the uploader; do not set RSYNC_URL, but do set S3_URL, IA_COLLECTION, IA_ITEM_TITLE, IA_AUTH, and IA_ITEM_PREFIX, and the items will go directly to IA.
Current functionality is undisturbed.
=> Support for uploading directly to IA

pipeline/archivebot/control.py, pipeline/pipeline.py
This lifts log line, byte count, and file count shipping to a worker thread with a queue, thus speeding up crawling considerably.  However, if the redis queue is slow, the queue may become quite long.
Also corrects a typo.
=> Async shipping of logs from pipelines to redis

pipeline/archivebot/control.py, uploader/uploader.py
Sometimes, a URL has a very long DNS name, resulting in a very long bucket name and very long filenames.  The IA S3 API rejects these, but cruelly does so with a 400 Bad Request error only after uploading is finished.  This guarantees that won't happen.  The left part is truncated to keep date and ID information and extensions.
This request also contains some code to reduce the number of redis transactions.
=> Limit transmitted filename and transmitted bucket DNS component to 64 bytes each for S3 uploads

uploader/uploader.py
sketchcow mentioned such filenames were causing trouble at IA.
=> Prevent filenames in IA uploader from starting with . and _

db/ignore_patterns/mediawiki.json
Semantic MediaWiki is a MediaWiki extension that has been getting popular.  ArchiveBot got stuck downloading a lot of cruft from one earlier.
List of Special pages to ignore lifted from https://www.semantic-mediawiki.org/wiki/Help:Blocking_robots_from_Semantic_MediaWiki_special_pages.
=> Add Semantic MediaWiki ignore patterns

db/ignore_patterns/twitter.json
Due to phantomjs, ArchiveBot grabs numerous copies of these.
=> Add Twitter analytics ignore patterns

db/ignore_patterns/forums.json
The important addition here is ignoring individual post URLs.
These could easily increase the number of pages about twenty-fold, yet (should) only hold redundant information.
=> More forums ignore patterns

.gitignore, .travis.yml, db/ignore_patterns/noonion.json, pipeline/archivebot/control_test.py, pipeline/archivebot/seesaw/wpullargs_test.py, pipeline/archivebot/wpull/ignoracle.py, pipeline/archivebot/wpull/ignoracle_test.py, test/validate_db.py
Failing tests are useless.  I fixed a handful and removed the rest for now.  If somebody wants to fix them, they're welcome to.
Meanwhile, I added an actually useful test validating the ignore pattern json files, so we don't end up with a missing comma for weeks again.  In fact, there was a json error in current master we probably weren't aware of, so you can see a nice example of a failure on this test: https://travis-ci.org/Sanqui/ArchiveBot/builds/239085990#L498
=> Fix or skip failing tests, add new test validating json

dashboard/dashboard.html, dashboard/dashboard3.html
Before this fix, if "Use a prediction service to load pages more quickly" was
enabled in Chrome, it would make DNS lookups on the hostname in every URL that
flew by in the dashboard.
https://www.chromium.org/developers/design-documents/dns-prefetching
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control
Credit for this commit goes to @ivan
=> dashboard: opt out of DNS prefetching to avoid making DNS lookups on every host

INSTALL.pipeline
Makes the setup more robust against network problems and ninjawedding downtime.
=> Use autossh in place of ssh

db/ignore_patterns/forums.json
E.g. https://www.simplemachines.org/community/index.php?board=1.0;sort=subject
=> Added ignore pattern for sort orders on SMF's forum listings

db/ignore_patterns/mediawiki.json
The current mediawiki ignore set includes an ignore for `oldid=\d+`. This means that only the current version of each wiki page is archived. However, the previous versions typically contain unique data which is not grabbed elsewhere, so this seems overzealous to me.
My suggestion is to replace this ignore with `diff=\d+`. This would archive old revisions, e.g. http://archiveteam.org/index.php?title=ArchiveBot&oldid=28812 (rendered) and http://archiveteam.org/index.php?title=ArchiveBot&action=edit&oldid=28812 (markup), but continue to ignore the diffs, e.g. http://archiveteam.org/index.php?title=ArchiveBot&diff=28812&oldid=28218, which can be reconstructed from the individual revisions and inflate the archive massively.
=> Replace ignore pattern causing all previous revisions of wiki pages to be ignored

pipeline/archivebot/dupespotter/dupes.py
ZFS (At least the 0.6.5.6 version included with Ubuntu) will return st_blocks == 1 for all sizes of truncations I tested. Checking for <2 makes is possible to run a pipeline on ZFS.
=> Support storing files on ZFS

db/ignore_patterns/reddit.json
Three new ignore patterns for the Reddit ignore set that I've been using manually for a while now.
* The first pattern ignores links to threads that only have UTM parameters. These come from an attribute `data-inbound-url` on thread links when you browse a subreddit. The same link without the UTM parameters can always be found in the `href` and `data-href-url` attributes on the same element, so these are just duplicates. However, it would be better to do this with a URL rewrite to remove the UTM parameters.
* The second pattern ignores some tracking pixels on the AMP version of Reddit. I'm not sure if we maybe want to ignore the AMP version entirely, but we can certainly ignore the tracking pixel.
* The third pattern ignores links that appear in a small box in the bottom right corner when …
=> Added some ignore patterns for tracking links and pixels on Reddit

db/ignore_patterns/forums.json
Simple Machines Forum's search (I think) has a captcha. The audio version of that captcha causes an infinite loop due to a `rand` parameter. Jobs 9kefnmifdalhkf9ycnznkbzsg and 6xr98h5jt8pcq0mif5ebv49l7 were affected by this, for example.
=> Ignore verification code/captcha on SMF which causes an infinite loop

db/ignore_patterns/global.json
VKontakte has migrated from `vkontakte.ru` to `vk.com` several years ago, but we're still only ignoring share links for the old domain.
=> Ignore VKontakte share link also on vk.com domain

db/ignore_patterns/global.json, db/ignore_patterns/noonion.json
I propose merging the noonion ignore set, which ignores `.onion` domains, into the global ignore set. Tor is not supported by any pipeline currently anyway, and even if it were implemented, we'd have to treat them specially anyway since we (for performance reasons) most likely wouldn't want to retrieve everything in a job through Tor but only hidden services.
=> Merge noonion igset into global igset

db/ignore_patterns/blogs.json
Super Socializer is a Wordpress plugin for integration of what they call "Social Login, Social Share and Social Comments". This ignore handles login URLs for LiveJournal, Twitch, Twitter, and Xing. Although the plugin apparently also supports login through Facebook, Google, Instagram, Linkedin, Steam, and Vkontakte, I wasn't able to find any such URLs. It's possible it directly inserts links to those platforms instead (e.g. `https://www.facebook.com/dialog/oauth`; cf. #278) rather than using the SuperSocializerAuth URL parameter, but I didn't check.
More information on the plugin can be found at https://wordpress.org/plugins/super-socializer/.
=> Ignore links by the Wordpress plugin "Super Socializer"

bot/command_patterns.rb, doc/commands.rst
Motivation: IRC crops long lines at a certain number of characters. If you add a too long pattern with !ig, it is impossible to remove it again because the line with !unig would be two characters too long. This alias works around that.
Cf. #218
=> Add !ug as an alias for !unignore

db/ignore_patterns/mediawiki.json
Special:PrefixIndex and Special:WhatLinksHere frequently cause recursion issues. What seems to happen is that there's a "what links here" link for the "what links here" pages, and similarly for the prefix indices. This might be a bug in certain versions of MediaWiki, but I haven't investigated further. Example jobs: dnyx2b04lif80aihvbfp9i6bc, de08ci8z5t22lkysv4ig7mcx1, dud6zbw6dh2m8ials08bdnf7k.
=> Ignore PrefixIndex and WhatLinksHere recursions on MediaWiki

db/ignore_patterns/global.json
The URL parameter for the Wordpress plugin Wordfence was renamed from `wordfence_logHuman` to `wordfence_lh` recently. It doesn't appear to be mentioned in the changelog or any other easily discoverable document, but it's mentioned e.g. [here](https://wordpress.org/support/topic/wordfence_loghuman1hid/).
=> Add ignore for new Wordfence URL parameter wordfence_lh

db/ignore_patterns/youtube.json
`!a` jobs for YouTube channels cause a recursion of www/www/www/www/www/... in the URLs. I haven't investigated where these come from, but we obviously don't want to grab them. For examples, see jobs 5i6xcnc3rbrw8atobna6zka5, c6oh9o424ia10gyraobqqh809, 8ukvohrhbx6syifk8va0kzhp9, and many more in early September.
=> Ignore /www/www/... recursion on recursive YouTube channel jobs

db/ignore_patterns/notumblrnoteavatars.json
Tumblr increased the resolution of note avatars at some point in the past few months from 16 x 16 px² to 64 x 64 px² on some stylesheets.
Unfortunately, this change has the side effect that the blogger's avatar might also be ignored on some pages. For example on [this blog](https://constable-frozen.tumblr.com/), the avatar appears as `_64.png` on the individual posts; however, it is also included as `_128.png` at the top of the page.
The only way to solve this properly would be to have conditional ignores depending on where on the page the image was found. I suppose this could be implemented in the `dupespotter`, similarly to the (currently broken) Drupal handling, but that would obviously be a lot more work.
=> Ignore higher resolution of Tumblr note avatars

uploader/uploader.py
The uploader used `-a`, i.e. `-rlptgoD`. All except `-t` were removed for the following reasons:
* `-r`: recusion isn't needed since each file is transferred individually anyway.
* `-l` and `-D`: all files we're transferring are regular files; support for symlinks and devices isn't needed.
* `-g` and `-o`: these cause issues if the files are owned by root:root on the pipeline machine. This can happen in particular in a Docker-based setup.
* `-p`: permissions are likewise unnecessary to transfer. Note that the uploads from within the pipeline (JSONs and WARCs in the case of crashed or killed wpull processes) never copied permissions to begin with; those use seesaw's RsyncUpload, which passes the options `-rltvz` to rsync.
Keeping the date of last modification of the file may be useful, …
=> Remove unnecessary rsync options in the uploader due to permission issues in some configurations and for simplicity

db/ignore_patterns/global.json
These streams seem to appear absolutely everywhere and have slowed down many a job before.
While I've only seen France Info, France Inter, and France Culture on ArchiveBot before, I decided to throw in the other Radio France stations as well.
The second part of the regex covers the CDN that actually hosts the streams; the URLs on direct.franceinfo.fr etc. are just redirects. Note that there are two separate streams: `/live/...` redirects to `chai5she.cdn.dvmr.fr`, `/ts/...` to `aechai9hib.cdn.dvmr.fr`. Examples:
* http://direct.franceinter.fr/live/franceinter-midfi.mp3 → http://chai5she.cdn.dvmr.fr:80/franceinter-midfi.mp3
* https://direct.franceinter.fr/ts/franceinter-midfi.mp3 → https://aechai9hib.cdn.dvmr.fr:443/franceinter-midfi.mp3
=> Add ignores for Radio France's streams (France Info/Inter/Culture/Musique/Bleu, FIP, and Mouv')

db/ignore_patterns/global.json
This domain is a sinkhole domain. IPs accessing it end up on a blacklist, specifically the CBL.
jap-porpoise was affected by this (but is now delisted). I haven't checked other pipelines' IP addresses.
=> Ignore sinkhole domain

pipeline/archivebot/wpull/ignoracle.py
As discussed in the IRC over the past few days, the ignoracle's performance can be improved by caching the patterns until either `primary_netloc` or `primary_url` change. This prevents repeatedly regex-escaping the values of those variables, replacing them in the regexes, and potentially recompiling the regexes (Python's `re` module caches up to 512 patterns internally) on every single call to `Ignoracle.ignores`.
You can find a basic performance analysis of this at https://github.com/JustAnotherArchivist/ArchiveBot/tree/ignoracle-performance
=> Cache the ignoracle patterns while primary_url and primary_netloc stay constant

bot/job_status_generation.rb
The job status is currently two verbose and spams the channel with four lines of log.
So instead of:
```
09:45:53 <+anarcat> !status 1wm191rekoxp02guomaxcwrpz
09:45:53 <Major> anarcat: Job 1wm191rekoxp02guomaxcwrpz <http://www.threehundredeight.com/>:
09:45:53 <Major> anarcat: Started by anarcat.
09:45:53 <Major> anarcat: In progress.  Downloaded 10915.47 MB, 1187 errors encountered, 0 items queued.
09:45:53 <Major> anarcat: 4 workers, delay: [0.0, 0.0] ms.
09:45:53 <Major> anarcat: See the ArchiveBot dashboard for more information.
```
We should be seeing something like:
```
09:45:53 <+anarcat> !status 1wm191rekoxp02guomaxcwrpz
09:45:53 <Major> anarcat: Job 1wm191rekoxp02guomaxcwrpz <http://www.threehundredeight.com/>. Started by anarcat. In progress. Downloaded 10915.47 MB, 1187 errors …
```
=> make job status less chatty

bot/brain.rb
`--youtube-dl` has been broken since May 2017, cf. #291. This errors out when someone tries to use it.
=> Disable youtube-dl until #291 is fixed

doc/commands.rst
It's in the source but not in the docs.
=> document the archive --large flag

bot/brain.rb
The job queue used to be disabled entirely until that restriction was removed last year due to the [observation](https://github.com/ArchiveTeam/ArchiveBot/issues/109#issuecomment-313533407) that "we have lots of capacity and it's somewhat rare for anything to be in the queue". This is definitely not true anymore. Even though our capacity is now larger than ever before, we still end up with huge job queues more often than not. Before yesterday, we last had an empty queue two weeks ago (for just a few hours!), and there were over 20 jobs pending during most of October, with a peak of 50 mid-month. This means that urgent jobs often don't start for days unless you explicitly bypass the queue.
A few of the active people in `#archivebot` discussed this in the past two days, and this PR is the …
=> Allow only opped users to add jobs when there is a queue of 5 or more jobs

pipeline/archivebot/seesaw/wpull.py, pipeline/archivebot/seesaw/wpullargs_test.py, pipeline/pipeline.py
The defaults might not fit every pipeline and are a bit low when it
comes to large file downloads. Make them configureable.
I don’t know how to run the test suite though.
=> Add WPULL_MONITOR_DISK/MEMORY env vars

dashboard/resources/recent.rb, plumbing/analyze-logs, plumbing/log-firehose
These are some error handlers which presumably work around conditions causing crashes on the control node. They've been in place on the production system for a long time but were never added to the repository for some reason, even though they should be useful for others wanting to run this. I have no idea what the background behind these changes was; I assume they were made by @yipdw, so direct all potential questions to him. :-)
=> Add some error handling

bot/command_patterns.rb, bot/job_options_parser.rb, doc/commands.rst
wpull's option is called --concurrent, so it makes sense to support that on ArchiveBot as well.
I often get confused by that discrepancy, and according to my logs, I'm not the only one who accidentally used --concurrent instead of --concurrency in the past.
=> Add alias --concurrent for !a/!ao command and !concurrent for !concurrency

db/user_agents/safari.json
Updated Safari UA for Mac OSX with the string for High Sierra
=> Update Safari UA

db/ignore_patterns/global.json
Not sure when this started, but lately we had a lot of jobs retrieve thousands of inexistent URLs from Squarespace due to wpull's JS extraction. The actual scripts are in .../scripts-compressed/; I haven't found any valid URLs in deeper directories.
=> Ignore Squarespace JS hell

db/ignore_patterns/github.json, db/ignore_patterns/nogithubcode.json
"github" is the general igset that should be used with GitHub grabs. "nogithubcode" ignores the code itself and should probably be used for any repository that isn't just a few commits and files large.
Explanations for the github ignores:
- search, find, blame, diffs, compare, and notifications are obvious redundant views or other unnecessary things.
- s, etc. are somehow related to keyboard shortcuts (wpull's JS extraction) and cause infinite loops.
- q=(.*\\+)?-?(label... ignores redundant views of issues and PRs (filtered by labels, milestones, author, etc.)
- The next three ignores handle sorting. I couldn't verify that projects, labels, and milestones will work correctly in the case of pagination because I couldn't find any repository with enough of those things to have pagination in …
=> Add igsets for GitHub

db/ignore_patterns/blogs.json
The ignore is specific enough that there shouldn't be any relevant false positives.
=> Ignore reverse pagination on custom Blogspot domains as well

db/ignore_patterns/blogs.json
The WordPress plugin [Fastest Cache](https://wordpress.org/plugins/wp-fastest-cache/) minifies JS and CSS, and wpull's naive JS URL extraction leads to deep recursion due to this. URLs of the minified JS/CSS are of the form `/wp-cache/cache/wpfc-minified/randomchars/file.ext` (where randomchars is some sort of hash over the file contents); there are no directories inside that path, and Fastest Cache always serves the same file based on only the hash (wpFastestCache.php lines 247 ff. in version 0.8.9.3).
=> Ignore WordPress Fastest Cache's minified JS recursion

.travis.yml, db/ignore_patterns/meetupeverywhere.json, test/run_pipeline.sh
* Bump Python version and run tests on both 3.5 and 3.6. Python 3.4 is unsupported, not used by any current pipeline (to my knowledge), and can no longer run lxml since a few weeks ago (version 4.4.0).
* Fix a broken ignore pattern in the meetupeverywhere igset
* Replace outdated deadsnakes PPA that hasn't been updated since 2017
* Work around https://github.com/pyenv/pyenv/issues/789 by directly running `/usr/bin/python3.6`
* Remove quiet flags on pip installs so we can see what's going on there
=> Update tests (August 2019)

db/ignore_patterns/global.json
`www<dot>cgzxb<dot>com` is associated with some malware, and accessing it causes a listing on the CBL.
=> Ignore a CBL sinkhole domain

uploader/uploader.py
https://github.com/ArchiveTeam/ArchiveBot/issues/305
Fixes issue 305.
=> Block uploading to an rsync URL that doesn't end in a slash

cogs/start.rb
The Broadcaster uses a ridiculous amount of CPU, and if tweeting's disabled, that's just a waste since nothing uses the messages.
=> cogs: Run the Broadcaster only if necessary, i.e. if tweeting is enabled

bot/bot.rb, bot/pipeline_notifier.rb, dashboard/resources/pipeline.rb, lib/pipeline_collection.rb
Fixes #332
Unfortunately, due to the simple implementation (no real memory, only inside the bot), the entire list of pipelines is announced to the channel when the IRC bot starts up. In other words, there'll be some spam after bot reboots. But I consider that the lesser evil compared to not being able to tell what pipeline an ID corresponds to down the line, and it can be fixed in the future if it becomes a problem. Fortunately, we don't need to restart the bot very often.
=> Notify IRC channel on pipeline changes

pipeline/pipeline.py
While the WARC files record the UTC date, log timestamps and filenames use the local timezone (but without any TZ indication). This discrepancy can be confusing and is completely unnecessary.
Pipeline operators, if you really must keep the time zone on your systems at some offset which is ambiguous once per year (DST), `export TZ=UTC` before running the pipeline.
=> Require that the time zone is set to UTC on pipelines

pipeline/pipeline.py
... to reduce the risk of pipelines running out of disk space.
=> Bump the default disk size limit from 500 MiB to 5 GiB

db/ignore_patterns/instagram.json
`?hl=` is the language switcher. Captions started appearing in URLs in early August; legitimate canonical post URLs are `/p/CODE/caption/SLUG` (i.e. no slash at the end).
=> Add basic Instagram igset

db/ignore_patterns/global.json
Squarespace moved their scripts to a different subdomain
#370
=> Adjust Squarespace JS hell ignore

db/ignore_patterns/blogs.json
The widget generates URLs for toggling the monthly or weekly archives in the sidebar.
This still lets it grab the entire tree on the homepage. The problem is when it starts doing that on every single page of the blog.
=> Ignore "BlogArchive" widget on Blogger

INSTALL.pipeline, ops/openssl-less-secure.cnf, pipeline/archivebot/seesaw/wpull.py, pipeline/pipeline.py
wpull's `--no-strong-crypto` allows for SSLv2 and SSLv3 connections (if the OpenSSL library is built accordingly) and compression.
The OpenSSL configuration file overrides the defaults that are shipped e.g. with Debian Buster, which only accept TLSv1.2+ and decently secure cipher suites.
Fixes #424 (hopefully)
=> Support weaker SSL/TLS connections for a broader compatibility with outdated web servers

db/ignore_patterns/mediawiki.json
On wikimedia wikis, CentralAuth is the pandora's box responsible for crazy amount of other WMF-wiki userpages. See mine [1] for example - it has 775*3 links[2] to WMF-sisterprojects as of 2019-12-26, and it only increases when the new wiki is added to WMF farm. Therefore it is sensible to remove them from the archive target.
[1]: https://w.wiki/EUG
[2]: Link to user page (domain itself), block log, and contribution link.
=> Include CentralAuth to mediawiki ignore rule

db/ignore_patterns/mediawiki.json
* Special:WikiPoints/global lists all users that have ever made an edit on any wiki in the network. The links to the users' profiles are all within the targeted wiki, so this blows up to millions and millions of URLs.
* Special:ListAllUsers is worse yet, listing all users registered on the network.
* Special:AllSites links to all wikis in the network.
=> Ignore pages on Gamepedia wikis that include things from the whole network

Gemfile, Gemfile.lock
https://github.com/lgierth/webmachine-sprockets was deleted or made private sometime between 2020-05-08 (https://web.archive.org/web/20200508141612/https://github.com/lgierth) and 2020-06-25 (#452). This breaks tests and new installations.
Replacing it with our own fork of the only copy remaining on GitHub
=> Fix webmachine-sprockets dependency

db/ignore_patterns/github.json
* First three additions are 404s (data-url, possible available with special headers or something).
* hovercard is 406.
* Package sorting.
* Scripts picked up by wpull's JS string extraction (might have some false positives but should be very rare).
=> Ignore various unnecessary or broken URLs on GitHub

db/ignore_patterns/global.json
Some of these files are gigantic, especially the ones in the S3 bucket (4K VR etc., the largest file is 620 GB as of right now), and they've caused a number of crashes recently due to filling disks.
This ignore would not cover the video files that are actually used on the site or in the embed when accessed with a browser. For example, https://littlstar.com/videos/633a96a1 and https://embed.littlstar.com/videos/633a96a1 play back video files https://littlstar.com/embed/proxy/videos/3186eccb-e9d2-4735-bc41-c71a3e2b29cb/web.mp4 and https://embed.littlstar.com/proxy/videos/3186eccb-e9d2-4735-bc41-c71a3e2b29cb/web.mp4, respectively. These are not currently extracted by wpull though.
=> Ignore Littlstar video files

db/ignore_patterns/github.json
* All searches on 'Actions'; there's heavy rate-limiting, and they're hardly useful anyway.
* used_by_list is 406.
* Updated script tags' data-module-id values
=> Ignore more unnecessary GitHub URLs

bot/bot.rb
Cinch's standard limits of 10 queue size and 0.5 per second are a bit odd. 1 per second is generally acceptable on most networks, but at least on hackint, a slightly lower queue size seems to be necessary to avoid messages getting swallowed by *something*.
=> Adjust IRC rate limits

db/ignore_patterns/badvideos.json
This igset is only intended as a temporary workaround until #443 is implemented properly.
Does not include the JW Player customer videos as those are not as frequent as the FastCo ones.
=> Add (temporary) badvideos igset

dashboard/resources/finished.rb
* Get rid of the extra `HGET` on every job due to the `Job.from_ident` implementation.
* Pipelined `HGETALL` calls
Overall, this brings the time down from 4.5 to 2.2 seconds in my test (just a simple `time curl`).
=> Improve performance of dashboard finished endpoint

pipeline/archivebot/seesaw/preflight.py, pipeline/pipeline.py
* Run the preflight test in the pipeline directory to avoid issues from different file systems (e.g. small /tmp, causing the disk space checker to pause everything).
* Replace the pseudo-invalid test domain with one that can never be valid.
* Run the preflight test before pipeline registration so failures don't require control node cleanup.
=> Pipeline preflight test improvements

pipeline/archivebot/wpull/ignoracle.py
`set_patterns` is called by `ListenerWorkerThread` and modifies variables used by the main wpull thread. This introduces several race conditions. For example, this means that `_compiled` may rarely get cleared during the iteration in `ignores`, and `patterns` might change during compilation.
For performance reasons, it's undesirable to use a lock on every call to `ignores`, especially as that method might get called many millions of times on large jobs. This implements an intermediate solution that avoids such locking. `_compiled` is only changed by the main thread, therefore the actual ignoring can't be affected by the updates. The updater thread might change `_primary` and `patterns` during or after the recompilation condition, however, such a change would always also require a …
=> Fix ignores sometimes not being applied correctly due to thread-related race conditions

pipeline/pipeline.py
All set environment variables will now be passed to wpull, including for example LD_LIBRARY_PATH and LD_PRELOAD and LANG.
=> Stop filtering the wpull environment

pipeline/archivebot/seesaw/dnspythoncrash.py, pipeline/pipeline.py, pipeline/requirements.txt
wpull depends on dnspython3, which is only a transitional package nowadays and hasn't been updated after 1.15.0, so that version is always used.
Supersedes #339, cf. ArchiveTeam/wpull#365.
=> Bump dnspython to 1.16.0

.travis.yml
Cf. https://github.com/pypa/get-pip/issues/61
=> Fix get-pip.py URL for Python 3.5 tests

ops/cookiejar-empty-hack.py
Cf. https://github.com/ArchiveTeam/wpull/issues/448
Based on https://gist.github.com/JustAnotherArchivist/8f5ac42a9c03302f222af3a58a863468
=> Add a hacky script for clearing a job's cookie jar

db/ignore_patterns/singletumblr.json
This lets jobs grab video iframes and offsite links that aren't Tumblr blogs (except custom domains).
=> Be looser on singletumblr igset

db/ignore_patterns/global.json
This appears on a lot of sites, and almost always times out, slowing down jobs. Other addthis.com domains are already ignored.
=> Globally ignore s7.addthis.com

db/ignore_patterns/github.json
Both of these are 406. `/sponsor_button` only appears on some repos, such as [this one](https://github.com/devkitPro/libogc/). `/hovercards/citation/sidebar_partial?tree_name=master` appears everywhere (but seems to usually be a 204 No Content outside of ArchiveBot). `/sponsors_list`, not included here, does work fine.
=> Add additional github ignores

INSTALL.pipeline, dashboard/dashboard.html, doc/admin.rst, doc/commands.rst
This makes the docs more relevant to anyone wanting to run their own instance of ArchiveBot.
It also removes an ugly hack on the dashboard which was specific to the ArchiveTeam instance as well.
=> Overhaul the documentation to remove all references of the ArchiveTeam instance

doc/commands.rst
Changes some documentation links, i.e. `www.bar.org` to `example.net`. `www.bar.org` links to a spam site, presumably since after the docs were published. `example.net` will never have this issue as an IANA-reserved name; if it ever does, we'll have greater worries on our hands.
=> Documentation: change "www.bar.org" links to "example.net" links

dashboard/assets/scripts/dashboard.js, dashboard/dashboard.html
=> dashboard: fix out-of-viewport log windows not being scrolled down in Chrome

dashboard/assets/scripts/dashboard.js
This fixes:
"when you hover over a log window, it stops scrolling as intended, but each time a new job is added at the top of the dashboard, the log window scrolls to the bottom. I'm pretty sure this wasn't the case before [...]."
Reported by @JustAnotherArchivist 
Diagnosis:
`JobsRenderer._createLogContainer` calls `this.applyFilter()`; `applyFilter` was scrolling all the log windows (with the intention of scrolling log windows made newly visible by the filter), but neglected to check whether they were `log-window-stopped`.
=> When a new job is added, don't scroll the stopped logged window being hovered over

ops/openssl-less-secure.cnf
Since OpenSSL 3.0, legacy renegotiation is disabled. This leads to 'Operation not permitted' errors e.g. on https://josour.unescwa.org/. With curl, it manifests as 'OpenSSL/3.0.11: error:0A000152:SSL routines::unsafe legacy renegotiation disabled'. Notably, browsers have no issues connecting there.
Further, the config file format apparently has to be more complicated now. It's still compatible with OpenSSL 1.1.1 though. I did not test older versions since they're irrelevant by now.
=> Reenable unsafe renegotiation (cf. RFC 5746) and update openssl.conf for OpenSSL 3.x

db/ignore_patterns/blogs.json
Cf. https://github.com/ArchiveTeam/wpull/issues/489 though they've been useless before that already, too.
=> Ignore Google and Outlook calendar links from the All-In-One Event Calendar (ai1ec) WordPress plugin

db/ignore_patterns/global.json
These are often generated by the [Tribe](https://tri.be/our-work/the-events-calendar/) [events calendar](https://theeventscalendar.com/) on wordpress sites, and always redirect to a generic login page (or an information page for the outlook.live.com variant). These pages aren't useful to save (especially as even if you have an account on one of these services, loading the login page on web.archive.org won't be helpful).
See demo pages [here](https://demo.theeventscalendar.com/events/month/) and [here](https://demo.theeventscalendar.com/event/cooking-for-busy-healthy-people/2023-03-14/). ArchiveBot doesn't do anything with the iCalendar link. The .ics links are per-site, and could maybe be added to the blogs igset (but these calendars also need manual work to limit pagination, so I don't …
=> Add Google and Outlook calendars to global ignoreset

db/ignore_patterns/nosortedindex.json
Recently I encountered a few jobs using software using a syntax like `?C=N&0=A` instead of `?C=N;0=A` for sorting index lists. This usually gets noticed only after a fair amount of those URLs made it into the job already. For that reason I’d like to add it to the ignoreset.
=> nosortedindex: Add alternate syntax

db/ignore_patterns/forums.json
`/share` is a "Share this post" page that contains no useful information (e.g. https://www.emutalk.net/posts/134368/share and https://www.emutalk.net/posts/123040/share).
`/page-%page%` is from a data attribute used for a page selector, but there's also a regular page selector that uses normal links so it can just be ignored.
`/poll/vote` is the (POST) action on a form tag (and can't be used without an account).
=> ignoresets: add some XenForo ignores

db/ignore_patterns/global.json
The site is long dead and just redirects to Yahoo now,
this slows down archiving of very old blogs/forums etc.
=> Global ignores: Geocities

db/ignore_patterns/global.json
MediaWiki automatically transcodes uploaded videos (and audio files) into several different formats. We don't need to save these transcoded versions (which are often reduced resolutions), only the original one, similar to how we already ignore image thumbnails.
=> Add transcoded Wikipedia videos to the global ignore set

db/ignore_patterns/badvideos.json
https://video.seattle.gov/ contains various large videos from the Seattle government. These are generally discovered from https://seattlechannel.org/ (which is in turn usually discovered from various local political sites).
The content is already mirrored at https://archive.org/details/seattlemunicipalarchives?tab=about or https://archive.org/details/sc21wa?tab=about (though the latter technically mirrors https://www.youtube.com/@SeattleChannel21/videos which has the same content). For instance, https://seattlechannel.org/videos?videoid=x159555 is mirrored at https://archive.org/details/sc21wa-Mayor_Harrell_unveils_bonus_rebates_for_heat_pump_upgrades (from https://www.youtube.com/watch?v=gC9TGn238Sc).
=> Add video.seattle.gov to badvideos ignore set

db/ignore_patterns/global.json
See https://web.archive.org/web/20220505195500/https://blog.stackpath.com/maxcdn-and-securecdn-are-retiring-heres-what-it-means-for-you/ and https://github.com/twitter/twemoji/issues/556 for context. Based on e.g. https://web.archive.org/web/20240710000000*/https://twemoji.maxcdn.com/2/72x72/1f43e.png it looks like twemoji.maxcdn.com used to redirect to cdn.jsdelivr.net (possibly with an invalid certificate, which archivebot ignores), but recently started timing out.
=> Add twemoji.maxcdn.com to the global ignore set
